config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #-- main
  root to: 'main#index'

  #-- ragnarok
  get 'ragnarok' => 'ragnarok#index'
  get 'ragnarok/medallions' => 'ragnarok#medallions'
  get 'ragnarok/items' => 'ragnarok#items'
  get 'ragnarok/units' => 'ragnarok#units'
  get 'ragnarok/search' => 'ragnarok#search'
end

app/views/layouts/application.html.slim
/ template: slim
doctype html
html
  head
    title VBS
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-toggle="collapse" data-target="#navbar" aria-expanded="false"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'VBS', root_path, class: 'navbar-brand'

        .navbar-collapse.collapse#navbar
          ul.nav.navbar-nav
            li= link_to 'RAGNAROK', ragnarok_path

    .container
      = yield

app/views/layouts/ragnarok.html.slim
/ template: slim
doctype html
html
  head
    title VBS -RAGNAROK-
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-toggle="collapse" data-target="#navbar" aria-expanded="false"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'RAGNAROK', root_path, class: 'navbar-brand'

        .navbar-collapse.collapse#navbar
          ul.nav.navbar-nav
            li= link_to '検索', ragnarok_search_path
            li= link_to 'ユニット', ragnarok_units_path
            li= link_to 'メダリオン', ragnarok_medallions_path
            li= link_to '装備', ragnarok_items_path

    .container
      = yield